function getDayInfo(day) {

    return getDays()[day]

}

function getDays() {

    return {
        1: {
            keyword: 'nezávislost',
            description: 'Je nezávislá a je schopná hluboké lásky. Rozhoduje se sama. Je chápavá, solidní, přesná a čestná. Je přímá a jasně se vyjadřuje. Má ráda novinky a pružně je zavádí. Má tvůrčí myšlení a dar využívat tvořivosti k prosazení svých cílů a hledání nových možností. Je pozitivní a chytrá. Je sebevědomá, cílevědomá, dynamická a vynalézavá. Spoléhá na sebe, tvrdě pracuje a má vitalitu. Obvykle má rychlý postup v zaměstnání. Je laskavá a je dobrým spolupracovníkem. Ráda pomáhá ostatním Ráda cestuje, dovede ocenit krásu a miluje život. Je si vědoma sama sebe. Má silného ducha a vůdčí sílu s jasným pohledem do budoucnosti. Lpí na svých názorech. Nemá ráda nepořádek, lenost, nedbalost, falešnou pýchu, sliby a pochlebování. Má ráda svobodu a špatně snáší nadvládu druhých. Někdy se na kratší nebo delší čas stáhne do soukromí. Pocit osamění. V honbě za sebeuplatněním nevidí druhé.',
            warning: 'Je tvrdošíjná. Prosazuje se značné „ego“ – je nesnesitelná. Pozor na závislost na druhých. Komplex méněcennosti. Pozor na zlost, vzteklost a obtíže v komunikaci, které mohou přivodit nepříjemné situace. Tvrdohlavost v partnerském vztahu. Je sobecká a je sama. Je zahleděná do sebe, mluví jen o sobě. Je žárlivá. Je panovačná. Těžce nese přerušení přátelství. Nepodaří-li se jí dosáhnout toho, co chtěla, propadá smutku, pesimismu, podráždění a depresi. Je neústupná. Nesnáší kritiku a sama ráda kritizuje. Je ovlivnitelná a sama ovlivňuje druhé. Rozhoduje se unáhleně a riskuje. Pozor na vnitřní pýchu. Pozor na utrácení nad poměry.'
        },
        2: {
            keyword: 'družnost',
            description: 'Je ohleduplná a dovede naslouchat druhým. Je oddaná a citově založená. Pracuje i pro druhé a dokáže se vcítit do druhého. Je družná a drží se v blízkosti rodiny. Je diplomatem. Je romantická a má umělecké sklony. Má jemnou povahu. Řídí se intuicí. Důležitá je harmonie. Ráda dává i dostává. Vážná rozhodnutí provede až po důkladném promyšlení. Chce mít partnera, v samotě je jí teskno. Při řešení problému je třeba hledat dohodu i za cenu kompromisu. Snadno se dá umlčet.',
            warning: 'Je přecitlivělá a zranitelná. Pozor na obviňování druhých. Pozor na manipulaci s druhými či závislost na nich. a to především na partnerovi. Pozor na malicherné spory. Vyvarovat se nedůvěřivosti, strachu a disharmonie. Chybí jí odvaha a ctižádostivost. Je nerozhodná. Může citově vydírat. Je zahořklá a hádavá. Má sklony k hromadění majetku. Nedokončuje rozpracovanou práci. Pozor na stravování. Pozor na hněv.'
        },
        3: {
            keyword: 'kamarádství',
            description: 'Je společenská a kamarádská. Má ráda lidi a má mnoho přátel. Je upřímná. Je činorodá a plná nápadů. Nemá strach z druhých lidí. V milostném vztahu chce být nezávislá. Velmi důležité je najít si partnera pro společnost. Je smělá, aktivní, spolehlivá a iniciativní. Chce po sobě zanechat stopu. Má ráda úspěchy. Má štěstí v lásce. Ráda cestuje. Obvykle to co chce vykonat, se nejdříve odehraje v její mysli. Má smysl pro oblékání. Důležité je být veselý a brát život takový, jaký je. Neplýtvat svojí energii. Věnovat se partnerovi a dětem. Snažit se o přizpůsobení. Zajímat se o všechny příležitosti a ihned je neodmítat.',
            warning: 'Pozor na zesměšňování druhých. Vyhýbat se povrchnosti. Je výstřední a příliš ctižádostivá. Je žárlivá a prchlivá. Je domýšlivá. Činí výčitky a kritizuje. Působí na city druhého. Je přecitlivělá a roztěkaná. Je nervózní. Pozor na zbytečné diskuse. Pozor na diktátorské sklony především doma.'
        },
        4: {
            keyword: 'vyrovnanost',
            description: 'Je praktická a vyrovnaná. Má ráda rutinu. Je rozhodná. Má dobré organizační schopnosti. Je spolehlivá a soucitná. Když má někoho ráda, tak je vřelá, štědrá a věrná. Je systematická a trpělivá. Tvrdě pracuje, aby dosáhla jistoty a stability, a to všude. Důležitou roli hraje pevný partnerský svazek. Vrozená nejistota ji vede k hromadění majetku. Vrozený instinkt ji nutí stále proti něčemu bojovat. Nerada utrácí.',
            warning: 'Může dojít ke ztrátě osobnosti až rezignaci. Je útočná až hrubá. Pozor na kritiku všeho. Pozor na sobeckost. Nerozhodovat se unáhleně. Pozor na melancholii.'
        },
        5: {
            keyword: 'vnímavost',
            description: 'Je otevřená, odvážná, energická a zásadová. Je ráda svým pánem. Je vnímavá. Má ráda pokrok a potřebuje pro svoji činnost prostor. Má ráda změny a není pro ni nic pevného. Má téměř magnetický vliv na lidi, má šarm. Je srdečná, veselá a pohotová. Je ochotná riskovat. Má dobrou logiku a výmluvnost. Ráda komunikuje s druhými. Je stále ve spěchu a ráda cestuje. Věnuje péči vzhledu a svému zdraví. Má ráda úspěch a ocenění. Má zájem o nové věci a jejich fungování. Je zvídavá. Má jasno v tom, co chce. Nemá ráda, když se jí říká, co a jak má dělat. Přelétavost z jedné věci na druhou. Je povrchní. Je třeba více trpělivosti. Vyhýbat se nudě.',
            warning: 'Je neurotická a uzavřená do sebe. Je náladová a nedůtklivá. Je konfliktní. V některých případech se z ní stává podvodník a lhář. V rozčilení je hrubá a podrážděná. Vnucuje své názory druhým. Má v sobě vnitřní napětí a snadno propadá stresu. Je nestálá. Pozor na záludnost ve vztazích.'
        },
        6: {
            keyword: 'harmonie',
            description: 'Tato osoba potřebuje lásku a teplo domova. Vše dělá proto, aby dosáhla harmonie. Hledá partnera pro celý život. Je laskavá, citlivá, ohleduplná a bezelstná. Miluje rodinu a lidi, žije řádným manželským životem. Je třeba si udělat čas na sebe i druhé. Má dobré vztahy k rodičům, dětem a přátelům. Má hodně přátel. Ráda pociťuje, že někam patří a má své místo. Je spravedlivá a vnímavá. Je jemná, s příjemným a vřelým hlasem. Je romantická a oddaná. Sex považuje za přirozenou součást naplnění vztahu. Má ráda luxus, miluje krásu a má umělecké nadání. Důležitá je práce v týmu. Ráda je ve společnosti krásných lidí. Je obvykle tzv. domácím typem. Je tajnůstkářská. Může se stát, že obtížněji hledá svého partnera, anebo dává podněty k rozchodu. Je naivní. Má nedostatek sebedůvěry. V zájmu udržení souladu v partnerském vztahu může dojít ke ztrátě její důstojnosti.',
            warning: 'Má sklony k lenosti. Je stále ve zbytečném spěchu a návalu emocí. Je pomstychtivá. Má sklony k závislosti na alkoholu a drogách. Stresující a nebezpečný je mimomanželský poměr. Snaží se uspokojit pouze své požadavky. Má nároky na pozornosti např. v práci. Pozor na sobeckost a obtěžování druhých. Pozor na posedlost.'
        },
        7: {
            keyword: 'zkušenost',
            description: 'Má dar naslouchat svému vnitřnímu hlasu. Tato osoba je citlivá a vnímavá. Pro svůj život potřebuje partnera. Často má názory duchovní povahy, vztah k životnímu prostředí a medicíně. Stává se aktivistou. Ráda pomáhá druhým. Věří sama sobě, přírodě, ostatním a životu. Velmi často se ocitá tváří v tvář výzvám, které jsou hybnou silou pro osobní růst. Dovede dobře analyzovat vzniklé situace. Nemluví naplano. Je dobrosrdečná, společenská, romantická a sentimentální. Je dobrým řečníkem a má sklony k umění. Je přátelská, sympatická a přitažlivá pro opačné pohlaví. Je bohatá bez materiálního bohatství. Má snahu si vše odzkoušet na své kůži a nedbá rad a varování těch, kteří již danou situaci prožili. Špatně snáší hlupáky, pokrytce a nepoctivost. Má ráda tajemství a tajnosti. Nerada se slepě řídí radami. Vyhýbá se myšlenkám typu „co by se stalo kdyby“. Je třeba nechat všemu přirozený průběh a nesnažit se něco zpomalovat.',
            warning: 'Je bezhlavá, úzkostlivá a přílišně nápadná. Pozor na naivitu ve vztazích, neboť často nerealisticky vnímá partnera. Má sklony k závislosti na alkoholu a drogách. Má sklony k intrikám, jež vedou až ke zničení druhého. Je neklidná a roztěkaná. Je prospěchářem. Neodpouští. Velmi rychle mění své názory. Zbytečně plýtvá energií a časem. Nepřemýšlí nad realizací plánů, ale bez rozmyslu je realizuje. Nemá úctu k práci druhých. Má trýznivé pocity. Nevnímá druhé.'
        },
        8: {
            keyword: 'rovnováha',
            description: 'Tato osoba má vysokou energii. Má vůdcovské sklony. Je inteligentní, bystrá a podnikavá. Má dobrou představivost a obrazotvornost. Je odhodlaná a pracovitá. Je trpělivá, pohotová, poctivá a vážná. Má pevnou vůli. Ke svému cíli jde přes řadu překážek a každou práci bere vážně. Důležitou roli hraje úspěch, odměna, peníze a postavení. Je sebevědomá a výkonná. Snaží se o materiální bohatství. Bude třeba stále udržovat rovnováhu mezi silou, energií a mocí, bohatstvím a citem, slávou a láskou, inteligencí a bystrostí apod. Důležitá je přizpůsobivost. Nezapomíná na křivdy.',
            warning: 'Je neústupná a tvrdošíjná při řešení nepříznivých situací a v boji s nepřáteli. Pozor na nenasytnost, moc, zneužívání postavení a peněz. Je melancholická. Je sobecká a nemá pochopení pro druhé. Ráda kritizuje a klame. Zapojuje se do různých pletek a je pomstychtivá. Je vychloubačná. Chce získat výhody pro sebe na úkor druhých. Manipuluje s druhými a nehraje „fér“. Bývá trudomyslná a chybí ji smysl pro humor. Je netolerantní. Při rozčilení dovede ničit vše kolem sebe. Pozor na alkohol a drogy. Pozor na pasivitu. Trápí se černými vzpomínkami a smutnou minulostí. Zaplétá se do různých milostných dobrodružství a afér. Rozšiřuje pomluvy. Je agresivní, panovačná, tvrdohlavá, svéhlavá a má sklon k terorizování druhých. Je to silné karmické číslo, a tak vždy to, co činí druhým, se jí vrátí, a to vícenásobně.'
        },
        9: {
            keyword: 'uvážlivost',
            description: 'Tato osoba má velkou citlivost a je spolehlivá. Pravdu řekne až po důkladném promyšlení. Skrývá se v ní víc, než je vidět. Má schopnost akceptovat se taková, jaká je. Chce být zachraňovatelem. Je přátelská a vážná. Hledá hlubší smysl života. Je ctižádostivá, tvůrčí a mocná. Je otevřená, upřímná, nezávislá a nebojácná. Dovede čelit velmi obtížným situacím. Tvrdě a usilovně pracuje. Je zodpovědná a má ráda pocty a slávu. Vynakládá hodně energie, aby získala obdiv a sympatie. Má organizační schopnosti. Stále je v pohybu a činnosti tak, aby dosáhla svého cíle. Spirituální zaměření. Dovede odpustit. Sklon k poznávání a vzdělávání. Svým způsobem je perfekcionista. Hledá partnera s obdobnými zájmy. Je skromná, až zakřiknutá. Nic neodkládá a vše řeší ihned, neboť věří, že rychlé a krajní řešení je nejlepší. Je vybíravá a někdy má sklon k výstřelkům. Vše bere příliš vážně a trápí se tím.',
            warning: 'Je nesnesitelná a nedůtklivá. Má strach z maličkostí. Je obtížně ovládnutelná. Je prchlivá a dá se snadno vyprovokovat. Je impulzivní, agresivní až krutá. Bezhlavě riskuje. Vytváří spory v manželství. Má negativní postoj k spolupracovníkům, přátelům a partnerovi. Je hněvivá a arogantní. Pozor na vnitřní neklid a drogy. Pozor na falešnou pýchu a pokrytectví. Je netolerantní a úzkoprsá. Odsuzuje druhé a hledá na nich vady. Má sklony k snobismu a kousavým poznámkám.'
        },
        10: {
            keyword: 'síla',
            description: 'Tato osoba je emocionálně velmi silná. Je nezávislá, soběstačná a hrdá. Je pracovitá, zásadová a sebevědomá. Střeží své soukromí. Dosahuje úspěchů až po tvrdé práci. Má sklony k vůdcovství. Dovede dobře prosazovat své cíle a zájmy. Je tvůrčí. Je vitální a oddaná své práci. Je soucitná. Má málo dobrých přátel. Nepodléhá náladám. Lpí na pocitu výjimečnosti. Nemá se upínat na jeden tzv. velký cíl a přitom ztrácet přehled o ostatních a někdy důležitějších cílech. Někdy strach či obava při prosazování svých cílů. Stahuje se do sebe. Vyhýbat se rutině.',
            warning: 'Je rezervovaná a uzavřená. Může dojít k dočasnému odloučení od rodiny. Je jí těžko porozumět. Je závislá na sedativech. Pozor na závislost na druhých lidech. Je zarputilá. Pozor na nadřazenost a odtažitost. Je neústupná, což způsobuje napětí ve vztazích. Pozor na hádky a alkohol.'
        },
        11: {
            keyword: 'citlivost',
            description: 'Tato osoba je citlivá a intuitivní. Má zájem o duchovní cestu. Je to charismatická osobnost. Má ráda druhé lidi. Je snílkem. je diplomatem. Má revoluční myšlení a autoritativní chování. Projevují se léčitelské schopnosti. Je perfekcionista. Cítí se dobře tam, kde se jedná o kolektivní rozhodování. Nerada sděluje druhým své city. Vědomě neublíží. Důležité je udržovat rovnováhu mezi dáváním a braním. Je potřebná harmonie především doma. Potřebný je denní odpočinek. Mne si ruce nebo kouše nehty.',
            warning: 'Je umíněná a jedovatá. Je zranitelná a prchlivá. Může dojít k nedorozumění. Dostává se do stavu nejistoty. Je někdy závislá na druhých. Pozor na hněv a emoce. Je tvrdohlavá a sobecká. Pozor na výbuchy vzteku. Pozor na povrchnost, snahu manipulovat s druhými a na konfrontaci.'
        },
        12: {
            keyword: 'všestrannost',
            description: 'Tato osoba je činorodá a myšlenkově bystrá. Je všestranná a profesionálně schopná. Je chytrá, oblíbená a přitažlivá. Vyniká v řadě oblastí. Má smysl pro rodinu. Je otevřená, přátelská, společenská a zvídavá. Je veselá, nezávislá a rychle chápající. Je cílevědomá a tvořivá. Ráda cestuje za poznáním a má radost ze života. Ráda vaří a má ráda slavnosti a oslavy. Dovede se snadno přizpůsobit. Potřebuje vedle sebe partnera bez problémů. Chrání své soukromí. Je příliš náročná. Nemá ráda, když se jí říká, že něco nedokáže. V životě může dojít ke zmatku a chaosu.',
            warning: 'Rozhoduje se chaoticky až na poslední chvíli. Pociťuje stavy úzkosti a napětí. Je impulzivní. Pozor na lhostejnost, uzavřenost a tvrdohlavost. Je umíněná, žárlivá a majetnická. Pozor na vztek, mstivost a prudké emoce. Chyby hledá v druhých.'
        },
        13: {
            keyword: 'zranitelnost',
            description: 'Je samostatná a ctižádostivá. Je věrná, otevřená a odpovědná. Je oddaným partnerem. Tvrdě pracuje pro získání materiální jistoty. Je praktická a spolehlivá. Stále hledá nové příležitosti a cíle. Je to vůdčí osobnost. Má ráda zodpovědnost. Je činorodá a aktivní. Je přizpůsobivá. Práce se stává koníčkem. Dovede inspirovat druhé. Dovede vytvořit bezpečí domova. Je zranitelná. Prosazuje se vliv dominantní osoby, rodičů, partnera nebo příbuzných. Má nedostatek sebedůvěry. Je dobré vyhýbat se rutině a jednotvárnosti.',
            warning: 'Je vznětlivá. Má někdy dojem, že je k ničemu. Je urážlivá a nedůtklivá. Chybí ji sebedůvěra. Dovede někdy velmi ublížit slovem. Pozor na výbuchy hněvu a konflikty. Pozor na zmatek v životě a extrémní přístupy k druhým – buď někoho miluje nebo nenávidí. Prosazuje své bez snahy o nalezení kompromisu. Pozor na zbytečná rizika. Silná závislost např. na jídle, alkoholu, drogách, sexu. lécích apod. Pozor na hádavost, vyprovokování scén a vyhraněné názory.'
        },
        14: {
            keyword: 'cílevědomost',
            description: 'Zařizuje si život podle sebe. Potřebuje bezpečné domácí prostředí a dobré povolání. Tvrdě pracuje a dovede vydělat peníze. Je dobrá v podnikání a obchodě. Je ohleduplná, pozorná a spolehlivá. Pouští se do velkých podniků. Je velmi aktivní. Je dobrosrdečná, moudrá a pohotová. Důležitá je změna, jež přináší nové podněty v činnosti. Může se projevit sklon k hudbě a někdy sklon ke spiritualitě nebo náboženství. Je ambiciózní, vytrvalá a plná nápadů. Je samostatná a zodpovědná. Je přitažlivá a přizpůsobivá. Rychle myslí a často i mluví. Chce co nejvíce využít nabízených příležitostí. Někdy ráda komunikuje pomocí symbolů nebo čísel. Nemá ráda, když jí někdo jiný radí. Snaha dodržovat staré, i když nefunkční zvyklosti. Vyhýbat se pohodlnosti až lenosti. Někdy snaha vyhnout se některým problémům. Sní o hmotném světě.',
            warning: 'Je vznětlivá a impulzivní. Těžko zapomíná na křivdy. Při vzniku potíží ihned vyhledává změny. Někdy se může stát diktátorem. Pozor na podceňování. Je třeba dbát zvýšené opatrnosti při výběru přátel. Je nervózní. Pozor na chybný odhad a nesprávné plánování. Zahazuje dobré příležitosti. Vymýšlí a přivolává sobě i druhým problémy. Pozor na alkohol a drogy. Je zbrklá.'
        },
        15: {
            keyword: 'odvaha',
            description: 'Je vnímavá, citlivá a nezávislá. je ambiciózní, aktivní a energická. Má kuráž a odvahu. Je hrdá a pracovitá. Má tvůrčí projev. Je starostlivá a laskavá. Rodina je pro ni vším. Někdy vyjadřuje své názory přímo bez zábran. Má ráda majetek a popularitu. Má ráda přepych a snaží se dosáhnout majetku. Má ráda volnost a nevázaný život. Je komunikativní a vtipná. Dovede ocenit krásu. Chce si vše vyzkoušet na sobě. Žárlivě střeží svoje soukromí. Je posedlá prací, získáváním financí či výživou apod. Naučit se přijímat realistické závazky.',
            warning: 'Je vzpurná. Velmi nepříjemně působí stres. Obtížnější poznání. Utrácí značné sumy a vede rozmařilý život. Je sentimentální. Někdy vybuchne a je hrubá. Pozor na emocionální nevyrovnanost. Někdy záliba ve vytváření extrémních životních situací a záliba v alkoholu apod. Je pomstychtivá a neústupná. Je tvrdošíjná při prosazování svých záměrů. Pozor na zlost, zlomyslnost a obviňování druhých.'
        },
        16: {
            keyword: 'přímočarost',
            description: 'Má jasný názor na to, co je v životě dobré a špatné. Ozývá se proti netoleranci. Má dobrou pozorovací schopnost. Má smysl pro harmonii a lad. Je něžná a milá. Má snahu dobře vycházet s druhými a pochopit, co potřebují. Vydrží dělat vše dlouho. Má ráda nezávislého partnera. Má léčitelské sklony a inklinuje k duchovnímu životu. Dovede léčit i sama sebe. Smysl života hledá v pomoci druhým. Mohou se objevit sklony k tzv. prorockým snům. Je soucitná a umí naslouchat druhým. Je ctižádostivá a společenská. Dovede na sebe převzít odpovědnost. Je to silná osobnost využívající intuice pro dosažení svých cílů. Má dobré analytické myšlení. Nesnáší dogmatiky. Chce si vše odzkoušet na své kůži. Někdy se přespříliš fixuje na rodinu či příbuzné. Má exhibicionistické sklony. Je třeba si vážit toho, co má. Více času věnovat partnerovi. Někdy žije v iluzích.',
            warning: 'Nemá ráda pravidla a omezení. Trpí nejistotou a duševním napětím. Pozor na pletichaření a intriky. Je opatrná a má obavu ze ztráty postavení. Neúspěch ji značně trápí. Život může být plný vzestupů a pádů. Je zahleděná příliš do sebe a tím ztrácí pojem o realitě. Je málo průbojná. Pozor na lenost. Je přecitlivělá. Pozor na zlost, emocionální nevyrovnanost a snahu zasahovat do života druhých. Je chladná a vypočítavá. Má sklon k provokování. Nemá ochotu vzít v úvahu názory druhých.'
        },
        17: {
            keyword: 'zdatnost',
            description: 'Tato osoba má sílu a je odvážná. Je citlivá a ctižádostivá. Má dobrou pozorovací schopnost. Je výkonná, bystrá a pracovitá. Má vůdcovské schopnosti. Velmi důležitý je milostný vztah. Je společenská. Mohou se projevit sklony k léčitelství. Dovede správně myslet a déle uvažovat. Úspěchů dosáhne ve zralém věku. Dosáhne bohatství. Má smysl pro realizaci svých plánů. Je materiálně založená. Má dobré logické myšlení. Hluboce věří v život a nepropadá panice. Je ambiciózní a odhodlaná. Hledá netradiční způsoby řešení vzniklých situací. Bere na sebe povinnosti. Při výběru přátel se výhradně obracet na členy rodiny anebo velmi dobré přátele. Jde přímo k cíli. Vyhýbat se manipulaci s druhými. Buď má snahu ovládat nebo je ovládána. Nedostatek sebedůvěry.',
            warning: 'Je náchylná k dramatickým citovým projevům. Někdy dělá scény. Je zlostná a vrtošivá. Někdy se jeví jako primadona. Je s ní obtížné soužití. Někdy její postoj přináší vnitřní konflikty. Je agresivní a dotěrná. Myslí jen na sebe. Je tvrdohlavá a panovačná. Nestrpí odpor. Pozor na posedlost úspěchem a majetkem. Prudká cesta vzhůru a pak zhroucení. Je paličatá a egoista. Projevuje se úzkost z neúspěchů.'
        },
        18: {
            keyword: 'odpovědnost',
            description: 'Tato osoba je silná a zdatná. Je přemýšlivá a má dobrou inteligenci. Je starostlivá a má ochraňovatelský vztah k lidem. Dovede získat inspiraci z vyšších zdrojů. Někdy sklon k filozofii. Je upřímná a zásadová. Dovede překonat obtížné situace. Je materialista a vše dělá pro získání majetku. Touží po uznání. Je chytrá a ambiciózní. Má organizační schopnosti a silnou vůli. Má sklon k experimentování. Má vyhraněné názory a chce mít vždy pravdu. Vyhýbá se chlubení svým majetkem, bohatstvím, mocí, úspěchem a postavením. Je citlivá na to, co řeknou druzí. Chce vědět vše o svém partnerovi. Nekritizovat druhé, ale snažit se je pochopit.',
            warning: 'Je ukvapená a ztřeštěná. Je hněvivá a nedůtklivá. Trpí vnitřními konflikty a napětím. Má nepokojnou mysl a sklony k melodramatičnosti. Nerovnováha energie vede k zdravotním obtížím. Je žárlivá. Život je plný dramatických změn. Nevyrovnaná energie narušuje každý přátelský vztah i manželství. Někdy bývá zlomyslná a neřestná. Pozor na hrubosti a krutosti. Pozor na karmu především v oblasti uznání. Pozor na předsudky, autoritářství a agresivitu. Je cynická a skeptická k životu.'
        },
        19: {
            keyword: 'účastenství',
            description: 'Má velkou sílu a elán. Je moudrá, chápavá a účastná. Je intelektuálně založená. Je trpělivá a snaží se vyhovět žádostem druhých. V milostných vztazích je oddaná. Chce porozumět partnerovi a je velkorysá. Vášnivě ochraňuje rodinu. Je ctěná a vážená. Je úspěšná a majetná. Obvykla pracuje tam, kde je dobře placená. Svým způsobem je průkopníkem ve své oblasti. Je vynalézavá a tvořivá. Je přímá a vitální při dosahování svých cílů. Má ráda privilegované postavení, a proto tvrdě pracuje, aby jej dosáhla. Má neochvějnou víru v sama sebe. Je vlídná a sebevědomá. Je nezávislá, až někdy osamocená. Není dobré, když ji někdo ignoruje, zneužívá nebo zklame. Příliš lpí na svých názorech a vysokých požadavcích.',
            warning: 'Je obtížné jí porozumět. Je nevyrovnaná a náladová. Pozor na nadřazenost a snahu být výjimečný. Je panovačná a nervózní. Je neurotická a nesoudná. Je žárlivá. Je tvrdohlavá a výbušná. Pozor na podlézavost především významným osobám. Pozor na zlobu a litování sama sebe. Tvrdošíjně jde za svými cíli. Ráda kritizuje druhé. Nedostatek sebedůvěry.'
        },
        20: {
            keyword: 'intuice',
            description: 'Tato osoba je citlivá, oddaná a laskavá. Pro tuto osobu je velmi důležitý partner. Milostný vztah hraje vážnou roli. Je trpělivá. Potřebuje lásku a něhu. Hledá harmonii. Je pečlivá a starostlivá. Má sklon k soucítění a spolupráci. Je otevřená. Dobře řeší spory, neboť se snaží o dohodu. Je tolerantní a umírněná. Je přemýšlivá. Špatně snáší samotu. Zaujímá vyhraněný postoj vůči druhým. Je náladová.',
            warning: 'Může dojít ke ztrátě sebeovládání. Je prchlivá. Je zlostná a vzteklá. Pozor na stres, neboť přináší problémy se zdravím. Je netrpělivá a nervózní. Rychle mění svůj názor. Pozor na citovou konfrontaci a emocionální projevy. Je nerozhodná a propadá smutku. Je bojácná a zranitelná. Pozor na manipulaci s druhými.'
        },
        21: {
            keyword: 'pochopení',
            description: 'Tato osoba má velký potenciál. Je citlivá, laskavá a tolerantní. Snaží se pochopit druhé. Je tvořivá a může pracovat v širokém okruhu činností. Je společenská a diplomatická. V milostném vztahu je ohleduplná a něžná. Velmi důležitá je pro ni komunikace. Umí se prosadit, takže dosáhne dobrého postavení v zaměstnání. Řídí se instinktem. Je optimista s pozitivním přístupem k životu. Má ráda úspěch a líbí se jí nové výzvy. Ráda spolupracuje s druhými. Někdy lpí na rodině. Má nedostatek sebedůvěry. Pro zájmy druhých nevidí sebe.',
            warning: 'Dovede šlehnout slovem. Je hněvivá a má sklony k rozzlobení. Je netrpělivá. Je úzkostlivá. Pozor na nadřazenost a konfrontaci. Pozor na střídání nálady a emocí. Pozor na chamtivost a vyvolávání sporů.'
        },
        22: {
            keyword: 'vytrvalost',
            description: 'Tato osoba je citlivá a laskavá. Potřebuje pro to oporu partnera. Je praktická a důkladná. Je metodická a má organizátorské schopnosti. Snadno provádí praktická rozhodnutí. Ve svém povolání je výkonná a přesná. Je úspěšná především na poli politickém. Touží po uskutečnění svých snů. Důležitou roli hraje domov a materiální zajištění rodiny. Je zodpovědná a spolehlivá. Má ráda povinnosti a harmonii. Vyhovuje jí rutinní činnost. Je starostlivá a štědrá. Sklon k hromadění materiálních hodnot a nereálnosti, jež převládají nad pocity. Potřebuje jistotu. Někdy nedovede přijímat dary. Pozor na přílišný sklon k práci (workholik). Nesnáší citovou konfrontaci.',
            warning: 'Je umíněná a neústupná. Pozor na problémy v manželství. Někdy má pocit křivdy. Pozor na výbuchy emocí. Starosti a strach o zajištění základních potřeb. Nedostatek sebedůvěry. Snaha manipulovat s druhými. Je nečestná, nedůtklivá a krutá. Je necitlivá k potřebám druhých. Je zranitelná.'
        },
        23: {
            keyword: 'samostatnost',
            description: 'Rozhoduje se sama a nedá se ovlivnit. Žije svůj vlastní život. Někdy se jeví, jako by chtěla volnost, ale ve skutečnosti potřebuje partnera. Je citlivá, něžná, milá a chce být milována. Je chápavá, bystrá a společenská. V práci obvykle nemá problémy a je pracovitá. Je velmi dobrá v podnikání. Má důvtip a je inteligentní. Je populární a oblíbená a často i slavná. Mohou se projevit výjimečné schopnosti. Touží po realizaci svých představ. Je upřímná a otevřená. Je přemýšlivá a má dobrou paměť. Je praktická a snadno se vyjadřuje. Tato osoba chce mít volnost a vystačí si sama. Někdy se chová dětinsky. Sklon k nepořádku. Skrývá city před ostatními. Je snílkem. Je třeba se vyhýbat vyčerpanosti.',
            warning: 'Je jí někdy těžko porozumět. Je to ošidná povaha. Těžko se s ní jedná o věcech, které neodpovídají její představě. Nepodaří-li se jí udržet rovnováhu, bude žít bez lásky, kromě vztahu k majetku. Je chladná, sobecká a necitlivá. Je náladová a výbušná. Utíká před zodpovědností. Je nesoustředěná. Pozor na přehánění, případně lži. Pozor na přelétavost ve vztazích a nestálost.'
        },
        24: {
            keyword: 'přívětivost',
            description: 'Tato osoba je velmi kamarádská, ochotná, velkorysá a starostlivá. Je citlivá, něžná, štědrá a laskavá. Má metodický přístup a je praktická. Má ráda harmonii a krásu. Velmi důležitý je pro ni rodinný život. Je vytrvalá a má organizátorské schopnosti. Je systematická a výkonná. Je pilná a konstruktivní. Má dobré srdce a snaží se pomáhat druhým. Hledá dohodu a snaží se vše vyjednat. Je romantik. Může se projevit sklon k hudbě. Je přesvědčena, že vše má svůj čas. Někdy sklon k oddalování řešení. Rozhoduje se opatrně a pomalu. Zodpovědnost a povinnosti bere příliš vážně. Spoléhá na druhé. Lpí na blahobytu a různých věcech či prestižním zaměstnání.',
            warning: 'Pozor na práci pod vlivem stresu. Je unáhlená a hněvivá. Je přecitlivělá a trpí nedostatkem jistoty. Je tajnůstkářská. Může zažít neúspěch a zradu. Pozor na deprese a výbuchy emocí. Je náladová a rozmrzelá. Někdy je pasivní až líná. Je nezodpovědná.'
        },
        25: {
            keyword: 'nenáročnost',
            description: 'Tato osoba je skromná a nenáročná. Je citlivá a laskavá. Pro svůj život potřebuje citlivého partnera. Je tvořící a zábavná. Má sklony k uměleckým směrům. Má dobrou představivost a má nadání. Sňatkem může získat bohatství. Ráda komunikuje, a to i prostřednictvím např. počítače. Umí naslouchat druhým. Je intuitivní, společenská a přitažlivá. Má dobré logické a analytické myšlení. Je praktická a trpělivá. Má smysl pro detaily. Dovede dobře využívat příležitosti.',
            warning: 'Potřebuje klid a snažit se přizpůsobit. Je třeba se vyhýbat zmatku v životě. Někdy reaguje nepředvídatelně. Chce si vše odzkoušet na své kůži. Má snahu odkládat to, co je třeba neodkladně řešit. Je emocionální a nerozhodná. Nedovede čelit stresovým situacím v lásce. Může mít obtížné dětství. Je roztěkaná a nestálá. Projevuje se dvojakost a nejasnost. Je náladová. Pozor na zlost. Někdy se bojí změn. Má starosti. Pozor na závislost na druhých. Myslí jen na sebe. Je přecitlivělá, podrážděná a pociťuje ublíženost.'
        },
        26: {
            keyword: 'průraznost',
            description: 'Tato osoba je citlivá, laskavá a chápající. Má velkou vnitřní sílu, která ji umožní překonat obtíže. Má organizátorské a vůdčí schopnosti. Vyznačuje se pronikavým úsudkem a nic jí neunikne. Je bystrá a může dělat cokoliv. Je ctižádostivá a velkorysá. Je nezávislá. Má oddělen osobní život od práce. Je pracovitá, houževnatá a úspěšná. Úspěchu a dobrého postavení dosáhne až ve zralém věku. Touží po citovém bezpečí. Je mírná a má dobré srdce. Je šlechetná a podporuje druhé. Ráda řeší problémy druhých. Je diplomatická a dovede inspirovat druhé. Je vstřícná, otevřená a přístupná. Je zodpovědná a dovede tvrdě pracovat, aby dosáhla úspěchu. Důležité jsou vztahy a kariéra. Dosáhne uznání až věhlasu.',
            warning: 'Potřebuje, aby o ni druzí projevovali zájem. Je nejistá a někdy až závislá na druhých. Bere vše vážně a je příliš horlivá a posedlá svými pocity. Je třeba se učti smyslu pro povinnost. Má problémy v lásce, a proto je velmi důležité vybírat partnera s co největší opatrností. Je chtivá, arogantní a přeceňuje se. Je třeba udržet rovnováhu z hlediska plnění karmických úkolů. Pozor na krutost a mstivost. Je přecitlivělá, náladová a agresivní. Cítí zášť k tomu, kdo jí ublížil. Trápí druhé. Je nesnesitelná především ve vedoucím postavení. Pozor na pýchu a emocionální napětí.'
        },
        27: {
            keyword: 'svědomitost',
            description: 'Tato osoba je citlivá, citová a intuitivní. Je poctivá, pragmatická a konzervativní. Nepodléhá novým směrům. Vyhýbá se povrchním vztahům. Velmi důležitou roli hraje milostný vztah. Je podnikavá. Dovede prosadit své plány a nápady. Je oddaná své rodině. Může dosáhnout bohatství. Snaží se o získání informací o životě a hledá smysl života. Cítí se dobře v přírodě a ráda pomáhá druhým. Důležitou roli hraje domov. Je bystrá a chápavá. Rozhoduje se po důkladném promyšlení.',
            warning: 'Hluboce prožívá zklamání. Citlivě reaguje na okolní situace. Velmi často podléhá iluzím. Bere vše velmi vážně. Je naivní. Sama sebe trestá. Myslí si, že je k ničemu. Má sklony k sebezničení. Pozor na závislost na drogách a alkoholu. Pozor na nervové zhroucení a úzkost. Pozor na sebevražedné pokusy. Pozor na pánovitost. Je náladová, zranitelná a uzavřená. Je nerozhodná. Má sklon ke kritizování druhých.'
        },
        28: {
            keyword: 'rozpornost',
            description: 'Tato osoba je nezávislá a snaží se uspět. Řídí se citem a pak rozumem. Důležitý je partnerský vztah a rodinná pohoda. Má smysl pro humor. Ráda má vše pod svojí kontrolou. Rozhoduje se sama za sebe. Má neochvějné vystupování na obranu svých práv. Je něžná, milující, vřelá a starostlivá. Než něco řekne, raději to realizuje. Má hodně přátel a známostí. Má zájem o všechno pokrokové a moderní. Má dobré vlohy pro podnikání. Je to dynamická a ambiciózní osoba. Je bystrá a rychle se rozhoduje. Je přímá, otevřená a chápavá. Oceňuje spolupráci a povzbuzuje druhé.',
            warning: 'Obvykle ji nelze omezovat. Nenechá se k ničemu přinutit. Je pasivní. Pochybuje o svých schopnostech. Je k druhým necitlivá. Je konfliktní, agresivní a dominantní. Může se dostavit možnost osamělosti. Je tvrdohlavá a impulzivní. Je prchlivá a agresivní. Někdy je nositelem hněvu a zášti. Je neústupná. Je zranitelná. Negativně působí na druhé. Je uzavřená a umíněná. Je výbušná a nepříjemná. Pozor na diktátorské sklony. Uráží a sekýruje druhé. Je přecitlivělá a nepřizpůsobivá.'
        },
        29: {
            keyword: 'nepřehlednost',
            description: 'Tato osoba je citlivá a vnímavá. Má velký potenciál mimosmyslového vnímání. Má schopnosti při hledání pravdy a moudrosti. Vyniká dobrými myšlenkovými postupy. Velmi důležitá je duchovní činnost. Dosáhne úspěchu po stránce hmotného zabezpečení a majetku. Je pracovitá, vytrvalá a vynalézavá. Má mnoho nápadů a silnou intuici. Je otevřená a má bystré logické uvažování. Snadno navazuje kontakty a je přitažlivá. Je duchaplná a pohotová v komunikaci. Často inspiruje nebo podněcuje druhé k tvorbě.',
            warning: 'Vyhýbat se nudě. Milostný vztah je nepřehledný. Těžko hovoří o svých citech. Má vysoké nároky na druhé. Je zranitelná. Může dojít k nebezpečným nedorozuměním. Má snahu spíš otupovat své city alkoholem a drogami, než je řešit. Je uzavřená a tajnůstkářská. Občas je výstřední. Nestálost přináší problémy v manželství. Projevuje se vnitřní nejistota a pocit osamělosti. Pozor na podráždění a výbušnost. Je vychytralá a puntičkářská. Pozor na hádavost, citové výbuchy a zklamání. Pozor na ukvapenost a chladnou manipulaci s druhými. Má obavy ze ztráty materiálních hodnot.'
        },
        30: {
            keyword: 'ráznost',
            description: 'Tato osoba vyniká tvůrčí představivostí a pronikavou bystrostí. Vzniklý problém nejdříve promyslí a pak se rozhodne. Má radikální názory na život Je vynalézavá. Má své kouzlo. V milostném vztahu je důležitá komunikace. Dovede tvrdě pracovat, aby dosáhla pohodlí a komfortu. Dělá několik věcí najednou. Má zvláštní filosofický způsob myšlení. Má sklony pomáhat trpícím. Je vřelá, přátelská a má smysl pro humor. Je společenská a temperamentní. Je činorodá a přizpůsobivá. Je tvořivá. Mnohdy ráda spí.',
            warning: 'Má vyhraněné názory na život. Obvykle nepřipustí prohru. Nesnese průměrnost. Má sklon brát vše jako legraci. Chce být středem pozornosti a je výstřední. Hledá na všem vady. Někdy zbytečně mrhá svojí energií a nedokončí to, co začala. Nedostatek sebevědomí. Dovede druhé srazit kritikou. Může zneužít svých předností pro získání toho, co chce od života dosáhnout. Je to složitá osoba a těžko ji lze pochopit a přinutit ke komunikaci. V některých věcech se jeví jako tyran. Je vypočítavá a má ostrý jazyk. Má skony manipulovat s druhými. Je nesoucitná, povrchní a nesoustředěná. Pomlouvá a obviňuje druhé. Pozor na žárlivost. Pozor na hádavost, konflikty a zmatek v životě. Je nepořádná a má sklon k lenošení. Sexuální nevyrovnanost.'
        },
        31: {
            keyword: 'motivace',
            description: 'Tato osoba vyniká vysokou mentální bystrostí. Je nenápadná a ochotná dělat vše pro dosažení úspěchů. Má ráda společnost a je ráda s inteligentními lidmi. Důležitá je komunikace. Je přímá, poctivá a velkorysá. Je něžná, věrná a ohleduplná. Dělá hodně pro rodinu. Je odvážná a má vůdcovské sklony. Je vstřícná, družná a má ráda společenský život. Důležitá je různorodost v její činnosti.',
            warning: 'Obvykle vystupuje v opozici. Potřebuje jistotu a bezpečí. Někdy nedokončí to, co započala a vzdává se svých cílů. Někdy si myslí, že druzí mají pracovat stejně jako ona. Je povrchní a nesvědomitá. Má schopnost klamat a lhát. Má sklony k podvodným jednáním. Je zlomyslná, panovačná a posměvačná. Je uzavřená. Využívá bezbrannosti druhých. Mohou nastat prudké a nečekané změny. Může dojít k nedorozumění a pocitu osamění. Může se stát plachou a nespolečenskou. Pozor na nadřazenost a pocit své výjimečnosti. Má nedostatek odvahy.'
        },
    }

}

export {getDayInfo}